### PR TITLE
NumSrcKS

### PR DESCRIPTION
**Pull request by kashefy**
Adds a knowledge source to drive a model that estimates the number of sources present in an audio stream.
New Hypothesis class included.
We still need to provide a properly trained model. But the implementation is ready.
This replaces the older PR #1

### CODE REVIEW

**Comment by hagenw** [comment]
Hi @kashefy,

I would prefer to change the name of the new `NumSrcsKS` to something like `NumberOfSourcesKS` as all other knowledge sources have complete names and no abbreviations. See also http://docs.twoears.eu/en/latest/dev/coding-style-guide/naming-conventions/#general

**Comment by kashefy** [comment]
Will do.

**Comment by ivo--t** [comment]
@kashefy , there is a conflict in DnnLocationKS. Can you check and resolve this first?

**Comment by kashefy** [comment]
Will do.

**Comment by kashefy** [comment]
I think I based this off of the wrong branch, will close this and open a new one to avoid confusion.

**Pull request closed without merging**
